name: solar system workflow
on:
    workflow_dispatch:
    push:
        branches:
            - main
            - 'feature/*'
env:
      MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
      MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
      MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
      
jobs:
    unit-testing:
        name: unit testing
        strategy:
          matrix:
            nodejs_version: [18,19,20]
            os:  [ubuntu-latest,macos-latest]
            execlude:
              - nodejs_version: 18
                os: macos-latest
        runs-on: ${{ matrix.os }}
        steps:
            - name: checkout
              uses: actions/checkout@v4
              
            - name: setup node js version ${{ matrix.nodejs_version }}
              uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.nodejs_version }}

            - name: install depend.
              run: npm install

            - name: unit test
              run: npm test

            - name: upload report to rtf
              uses: actions/upload-artifact@v3
              with:
                name: report-test.txt
                path: test-results.xml